services:
  prometheus:
    image: prom/prometheus:latest
    container_name: arsw-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:latest
    container_name: arsw-grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
      - loki

  loki:
    image: grafana/loki:latest
    container_name: arsw-loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yml
    volumes:
      - ./loki/loki-config.yml:/etc/loki/local-config.yml

  promtail:
    image: grafana/promtail:latest
    container_name: arsw-promtail
    volumes:
      - ./promtail/promtail-config.yml:/etc/promtail/config.yml
      - ./logs:/var/log/appdemo
    command: -config.file=/etc/promtail/config.yml
    depends_on:
      - loki