server: 
  port: 8081 

spring:
  application:
    name: observability-demo

management: 
  endpoints: 
    web: 
      exposure: 
        include: health,info,metrics,prometheus 
  endpoint: 
    health: 
      show-details: always 
  metrics: 
    tags: 
      application: observability-demo

logging: 
  level: 
    root: INFO 
    edu.eci.arsw.observability: DEBUG